global:

templates:
- '/etc/templates/alertmessage.tmpl'

route:
 group_by: [alertname, job]
 # If an alert isn't caught by a route, send it to slack.
 receiver: slack_general
 routes:
  - match:
      severity: slack
    receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#prometheus'
    send_resolved: true
